# Generated by Django 5.2 on 2025-04-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_unit_phone_unit_whatsapp_alter_unit_bedrooms_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='down_payment_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
